version: '3'

services:
  db:
    image: mysql:8.0.25
    container_name: db
    restart: always
    secrets:
      - mysql_root
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root
      MYSQL_DATABASE: donuts
    ports:
      - "6033:3306"
    volumes:
      - /Users/jmcc/Dropbox/Docker/mysql:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
  voyager_donuts:
    container_name: voyager_donuts
    build:
      context: .
      dockerfile: Dockerfile
    image: voyager_donuts
    ports:
      - "5950:5950"
  admin:
    image: adminer
    ports:
      - "8080:8080"

secrets:
  mysql_root:
    file: ./secrets/mysql_root

