version: '3'

services:
  db:
    image: mysql:8.0.25
    container_name: db
    restart: always
    secrets:
      - mysql_root
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root
      MYSQL_DATABASE: donuts
    volumes:
      - d:/Dropbox/Docker/mysql:/var/lib/mysql
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    network_mode: "host"

  voyager_donuts:
    container_name: voyager_donuts
    build:
      context: .
      dockerfile: Dockerfile
    image: voyager_donuts
    network_mode: "host"
    volumes:
      - c:/Users/user/Documents/Voyager/DonutsCalibration:/voyager_calib

  admin:
    image: adminer
    network_mode: "host"

secrets:
  mysql_root:
    file: ./secrets/mysql_root
